version: "3.8"

# For DataNode setup, graylog starts with a preflight UI, this is a change from just using OpenSearch/Elasticsearch.
# Please take a look at the README at the top of this repo or the regular docs for more info.

services:
  mongodb:
    image: "mongo:5.0"
    volumes:
      - "/mnt/data/mongodb/db:/data/db"
    networks:
      - mongodb-internal

  # For DataNode setup, graylog starts with a preflight UI, this is a change from just using OpenSearch/Elasticsearch.
  # Please take a look at the README at the top of this repo or the regular docs for more info.
  datanode:
    image: "${DATANODE_IMAGE:-graylog/graylog-datanode:5.2}"
    hostname: "datanode"
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      GRAYLOG_DATANODE_PASSWORD_SECRET: graylog-password-secret
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: graylog-root-password-sha2
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    secrets:
      - graylog-password-secret
      - graylog-root-password-sha2
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    #ports:
    #  - "8999:8999/tcp" # DataNode API
    #  - "9200:9200/tcp"
    #  - "9300:9300/tcp"
    volumes:
      - "/mnt/graylog-datanode:/var/lib/graylog-datanode"
    networks:
      - mongodb-internal
      - graylog-internal
    depends_on:
      - mongodb

  graylog:
    hostname: "server"
    image: "${GRAYLOG_IMAGE:-graylog/graylog:5.2}"
    depends_on:
      - mongodb
    entrypoint: "/usr/bin/tini --  /docker-entrypoint.sh"
    secrets:
      - graylog-password-secret
      - graylog-root-password-sha2
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      GRAYLOG_PASSWORD_SECRET: graylog-password-secret
      GRAYLOG_ROOT_PASSWORD_SHA2: graylog-root_password-sha2
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://{{.Node.Hostname}}:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    #ports:
    # - "5044:5044/tcp" # Beats
    #  - "5140:5140/udp" # Syslog
    #  - "5140:5140/tcp" # Syslog
    #  - "5555:5555/tcp" # RAW TCP
    #  - "5555:5555/udp" # RAW TCP
    #  - "9000:9000/tcp" # Server API
    #  - "12201:12201/tcp" # GELF TCP
    #  - "12201:1229000tcp" # GELF UDP
    #  #- "10000:10000/tcp" # Custom TCP port
    #  #- "10000:10000/udp" # Custom UDP port
    #  - "13301:13301/tcp" # Forwarder data
    #  - "13302:13302/tcp" # Forwarder config
    volumes:
      - "/mnt/data/graylog/data:/usr/share/graylog/data/data"
      - "/mnt/data/graylog/journal:/usr/share/graylog/data/journal"
    networks:
      - traefik-public
      - graylog-internal
      - mongodb-internal
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cms.tls=true"
        - "traefik.http.routers.cms.service=cms"
        - "traefik.http.routers.cms.rule=Host(`log.coastalsites.dev`)"
        - "traefik.http.routers.cms.entrypoints=websecure"
        - "traefik.http.routers.cms.tls.certresolver=leresolver"
        - "traefik.http.services.cms.loadbalancer.server.port=9000"
        # Change the auth password here
        #- "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$05$$ZaVPNLwkafIJnxKRLScQcOpgyxyaD14Xn95j/rPS.Hs/AUru3WalO"
        #- "traefik.http.routers.cms.middlewares=auth"

networks:
  traefik-public:
    external: true
  graylog-internal:
    external: true
  mongodb-internal:
    external: true

secrets:
  graylog-password-secret:
    external: true
  graylog-root-password-sha2:
    external: true
