version: "3.8"

services:
  minio1:
    image: minio/minio:latest
    hostname: minio1
    networks:
      - traefik-public
      - minio-internal
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: JHY4zoQMXqbqj
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: minio1,minio2,minio3,minio4
    command: server --console-address ":9001" http://minio{1...4}/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - /mnt/data/minio/minio1:/data
    deploy:
      labels:
        - "traefik.enable=true"

        # MINIO console
        - "traefik.http.routers.minio1.tls=true"
        - "traefik.http.routers.minio1.service=minio1"
        - "traefik.http.routers.minio1.rule=Host(`minio.coastalsites.dev`)"
        - "traefik.http.routers.minio1.entrypoints=websecure"
        - "traefik.http.routers.minio1.tls.certresolver=leresolver"
        - "traefik.http.services.minio1.loadbalancer.server.port=9001"
        - "traefik.http.services.minio1.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.minio1.loadbalancer.sticky.cookie.secure=true"
        # MINIO api
        - "traefik.http.routers.miniocdn1.tls=true"
        - "traefik.http.routers.miniocdn1.service=miniocdn1"
        - "traefik.http.routers.miniocdn1.rule=Host(`s3.coastalsites.dev`)"
        - "traefik.http.routers.miniocdn1.entrypoints=websecure"
        - "traefik.http.routers.miniocdn1.tls.certresolver=leresolver"
        - "traefik.http.services.miniocdn1.loadbalancer.server.port=9000"
        - "traefik.http.services.miniocdn1.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.miniocdn1.loadbalancer.sticky.cookie.secure=true"
  minio2:
    image: minio/minio:latest
    hostname: minio2
    networks:
      - traefik-public
      - minio-internal
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: JHY4zoQMXqbqj
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: minio1,minio2,minio3,minio4
    command: server --console-address ":9001" http://minio{1...4}/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - /mnt/data/minio/minio2:/data
    deploy:
      labels:
        - "traefik.enable=true"

        # MINIO console
        - "traefik.http.routers.minio2.tls=true"
        - "traefik.http.routers.minio2.service=minio2"
        - "traefik.http.routers.minio2.rule=Host(`minio.coastalsites.dev`)"
        - "traefik.http.routers.minio2.entrypoints=websecure"
        - "traefik.http.routers.minio2.tls.certresolver=leresolver"
        - "traefik.http.services.minio2.loadbalancer.server.port=9001"
        - "traefik.http.services.minio2.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.minio2.loadbalancer.sticky.cookie.secure=true"
        # MINIO api
        - "traefik.http.routers.miniocdn2.tls=true"
        - "traefik.http.routers.miniocdn2.service=miniocdn2"
        - "traefik.http.routers.miniocdn2.rule=Host(`s3.coastalsites.dev`)"
        - "traefik.http.routers.miniocdn2.entrypoints=websecure"
        - "traefik.http.routers.miniocdn2.tls.certresolver=leresolver"
        - "traefik.http.services.miniocdn2.loadbalancer.server.port=9000"
        - "traefik.http.services.miniocdn2.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.miniocdn2.loadbalancer.sticky.cookie.secure=true"

  minio3:
    image: minio/minio:latest
    hostname: minio3
    networks:
      - traefik-public
      - minio-internal
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: JHY4zoQMXqbqj
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: minio1,minio2,minio3,minio4
    command: server --console-address ":9001" http://minio{1...4}/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - /mnt/data/minio/minio3:/data
    deploy:
      labels:
        - "traefik.enable=true"

        # MINIO console
        - "traefik.http.routers.minio3.tls=true"
        - "traefik.http.routers.minio3.service=minio3"
        - "traefik.http.routers.minio3.rule=Host(`minio.coastalsites.dev`)"
        - "traefik.http.routers.minio3.entrypoints=websecure"
        - "traefik.http.routers.minio3.tls.certresolver=leresolver"
        - "traefik.http.services.minio3.loadbalancer.server.port=9001"
        - "traefik.http.services.minio3.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.minio3.loadbalancer.sticky.cookie.secure=true"
        # MINIO api
        - "traefik.http.routers.miniocdn3.tls=true"
        - "traefik.http.routers.miniocdn3.service=miniocdn3"
        - "traefik.http.routers.miniocdn3.rule=Host(`s3.coastalsites.dev`)"
        - "traefik.http.routers.miniocdn3.entrypoints=websecure"
        - "traefik.http.routers.miniocdn3.tls.certresolver=leresolver"
        - "traefik.http.services.miniocdn3.loadbalancer.server.port=9000"
        - "traefik.http.services.miniocdn3.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.miniocdn3.loadbalancer.sticky.cookie.secure=true"

  minio4:
    image: minio/minio:latest
    hostname: minio4
    networks:
      - traefik-public
      - minio-internal
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: JHY4zoQMXqbqj
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: minio1,minio2,minio3,minio4
    command: server --console-address ":9001" http://minio{1...4}/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - /mnt/data/minio/minio4:/data
    deploy:
      labels:
        - "traefik.enable=true"

        # MINIO console
        - "traefik.http.routers.minio4.tls=true"
        - "traefik.http.routers.minio4.service=minio4"
        - "traefik.http.routers.minio4.rule=Host(`minio.coastalsites.dev`)"
        - "traefik.http.routers.minio4.entrypoints=websecure"
        - "traefik.http.routers.minio4.tls.certresolver=leresolver"
        - "traefik.http.services.minio4.loadbalancer.server.port=9001"
        - "traefik.http.services.minio4.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.minio4.loadbalancer.sticky.cookie.secure=true"
        # MINIO api
        - "traefik.http.routers.miniocdn4.tls=true"
        - "traefik.http.routers.miniocdn4.service=miniocdn4"
        - "traefik.http.routers.miniocdn4.rule=Host(`s3.coastalsites.dev`)"
        - "traefik.http.routers.miniocdn4.entrypoints=websecure"
        - "traefik.http.routers.miniocdn4.tls.certresolver=leresolver"
        - "traefik.http.services.miniocdn4.loadbalancer.server.port=9000"
        - "traefik.http.services.miniocdn4.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.miniocdn4.loadbalancer.sticky.cookie.secure=true"

networks:
  traefik-public:
    external: true
  minio-internal:
