version: "3.8"

services:
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PogJW_a9xXA73__T
    volumes:
      - /mnt/data/postgres:/var/lib/postgresql/data
    networks:
      - app-internal
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.postgres.entrypoints=postgres"
        - "traefik.tcp.routers.postgres.tls.certresolver=leresolver"
        - "traefik.tcp.services.postgres-service.loadbalancer.server.port=5432"
        - "traefik.tcp.routers.postgres.service=postgres"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: support@coastalsites.dev
      PGADMIN_DEFAULT_PASSWORD: 9zJTR4fWid-xiJmh
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
      # Number of values to trust for X-Forwarded-For
      PROXY_X_FOR_COUNT: 2
      # Number of values to trust for X-Forwarded-Proto.
      PROXY_X_PROTO_COUNT: 2
      # Number of values to trust for X-Forwarded-Host.
      PROXY_X_HOST_COUNT: 2
      # Number of values to trust for X-Forwarded-Port.
      PROXY_X_PORT_COUNT: 2
      # Number of values to trust for X-Forwarded-Prefix.
      PROXY_X_PREFIX_COUNT: 2
    command: 
      - -c 
      - ssl=off  
    volumes:
      - /mnt/pgadmin:/var/lib/pgadmin
    networks:
     - traefik-public
     - app-internal
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.postgres.rule=HostSNI(`postgres.coastalsites.dev`)"
        - "traefik.tcp.routers.postgres.entrypoints=postgres"
        - "traefik.tcp.routers.postgres.tls.certresolver=leresolver"
        - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"
networks:
  traefik-public:
    external: true
  app-internal:
    external: true
