version: "3.8"

services:
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PogJW_a9xXA73__T
    volumes:
      - /mnt/data/postgres:/var/lib/postgresql/data
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/data/ssl/certificate.pem -c ssl_key_file=/var/lib/postgresql/data/ssl/privatekey.pem
    networks:
      - app-internal
      - traefik-public
    ports:
      - "5433:5432"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.postgres.entrypoints=postgres"
        - "traefik.tcp.routers.postgres.tls.certresolver=leresolver"
        - "traefik.tcp.services.postgres.loadbalancer.server.port=5433"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: support@coastalsites.dev
      PGADMIN_DEFAULT_PASSWORD: 9zJTR4fWid-xiJmh
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
      # Number of values to trust for X-Forwarded-For
      PROXY_X_FOR_COUNT: 2
      # Number of values to trust for X-Forwarded-Proto.
      PROXY_X_PROTO_COUNT: 2
      # Number of values to trust for X-Forwarded-Host.
      PROXY_X_HOST_COUNT: 2
      # Number of values to trust for X-Forwarded-Port.
      PROXY_X_PORT_COUNT: 2
      # Number of values to trust for X-Forwarded-Prefix.
      PROXY_X_PREFIX_COUNT: 2
    volumes:
      - /mnt/pgadmin:/var/lib/pgadmin
    networks:
     - traefik-public
    deploy:
      labels:
        # change the host here
        - "traefik.enable=true"
        - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.coastalsites.dev`)"
        - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
        - "traefik.http.routers.pgadmin.entrypoints=websecure"
        - "traefik.http.routers.pgadmin.tls=true"
        - "traefik.http.routers.pgadmin.tls.certresolver=leresolver"
        # Change the auth password here

networks:
  traefik-public:
    external: true
  app-internal:
    external: true
